version: "3.8"
services:
  ui:
    build: ./docker/ui 
    volumes: 
      - .:/frontend
    environment: 
      PORT: '3000'
      HOST: '0.0.0.0'
      BASE_URL: 'http://nginx'
    ports: 
      - 3000:3000
    ## コンテナが落ちるため
    tty: true
    networks:
      - sample-spa

networks:
  sample-spa:
    external: true
    